/*
 * ironsim — Network Emulator
 * Spawns multiple ironstack instances connected by virtual links.
 * Supports link impairments (delay, loss, reorder) via tc netem.
 *
 * Usage: sudo ./ironsim [topology.conf]
 * Default: 2-node linear topology
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <unistd.h>
#include <signal.h>
#include <sys/wait.h>
#include <sys/types.h>

#define MAX_NODES    8
#define MAX_LINKS    8
#define MAX_IFACES   4   /* Max interfaces per node */
#define MAX_NAME     32
#define MAX_PATH     256

typedef struct {
    char ip[32];
    int  prefix_len;
    char tap_name[MAX_NAME];
} node_iface_t;

typedef struct {
    char name[MAX_NAME];
    node_iface_t ifaces[MAX_IFACES];
    int iface_count;
    pid_t pid;
    char conf_path[MAX_PATH];
} sim_node_t;

typedef struct {
    int node_a;
    int node_b;
    int iface_a;  /* Which interface on node A */
    int iface_b;  /* Which interface on node B */
    int delay_ms;
    int loss_pct;   /* 0-100 */
    int reorder;    /* boolean */
} sim_link_t;

static sim_node_t g_nodes[MAX_NODES];
static int g_node_count = 0;
static sim_link_t g_links[MAX_LINKS];
static int g_link_count = 0;
static volatile int g_running = 1;
static char g_ironstack_path[MAX_PATH] = "./ironstack/ironstack";

static void signal_handler(int sig) {
    (void)sig;
    g_running = 0;
}

/* ---- System commands ---- */

static int run_cmd(const char *fmt, ...) {
    char cmd[512];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(cmd, sizeof(cmd), fmt, ap);
    va_end(ap);
    return system(cmd);
}

/* ---- Config generation ---- */

static void generate_node_conf(sim_node_t *node) {
    snprintf(node->conf_path, MAX_PATH, "/tmp/ironsim_%s.conf", node->name);
    FILE *f = fopen(node->conf_path, "w");
    if (!f) { perror("fopen"); return; }

    fprintf(f, "# Auto-generated by ironsim for node %s\n", node->name);

    for (int i = 0; i < node->iface_count; i++) {
        node_iface_t *ifc = &node->ifaces[i];
        snprintf(ifc->tap_name, MAX_NAME, "iron-%s%d", node->name, i);
        fprintf(f, "interface %s mac 02:00:00:%02x:%02x:%02x ip %s/%d\n",
                ifc->tap_name,
                (unsigned)(node->name[0]), i, 1,
                ifc->ip, ifc->prefix_len);

        /* Connected route */
        int a, b, c, d;
        sscanf(ifc->ip, "%d.%d.%d.%d", &a, &b, &c, &d);
        fprintf(f, "route %d.%d.%d.0/%d dev %s\n", a, b, c, ifc->prefix_len, ifc->tap_name);
    }

    /* Add routes to remote subnets via linked peers */
    for (int li = 0; li < g_link_count; li++) {
        sim_link_t *l = &g_links[li];
        int my_idx = -1, peer_idx = -1, my_iface = -1;
        if (l->node_a == (int)(node - g_nodes)) { my_idx = l->node_a; peer_idx = l->node_b; my_iface = l->iface_a; }
        else if (l->node_b == (int)(node - g_nodes)) { my_idx = l->node_b; peer_idx = l->node_a; my_iface = l->iface_b; }
        if (my_idx < 0) continue;

        sim_node_t *peer = &g_nodes[peer_idx];
        /* Add routes to all of peer's subnets that aren't directly connected */
        for (int pi = 0; pi < peer->iface_count; pi++) {
            /* Skip the directly connected subnet */
            int pa, pb, pc, pd, ma, mb, mc, md;
            sscanf(peer->ifaces[pi].ip, "%d.%d.%d.%d", &pa, &pb, &pc, &pd);
            sscanf(node->ifaces[my_iface].ip, "%d.%d.%d.%d", &ma, &mb, &mc, &md);
            if (pa == ma && pb == mb && pc == mc) continue; /* Same subnet, skip */

            fprintf(f, "route %d.%d.%d.0/%d via %s dev %s\n",
                    pa, pb, pc, peer->ifaces[pi].prefix_len,
                    peer->ifaces[pi].ip,
                    node->ifaces[my_iface].tap_name);
        }
    }

    /* Permit all traffic */
    fprintf(f, "acl permit icmp any any port 0\n");
    fprintf(f, "acl permit tcp any any port 7\n");
    fprintf(f, "acl permit tcp any any port 8080\n");

    fclose(f);
    printf("  [ironsim] Config: %s (%d interfaces)\n", node->conf_path, node->iface_count);
}

/* ---- Node management ---- */

static pid_t spawn_node(sim_node_t *node) {
    pid_t pid = fork();
    if (pid < 0) { perror("fork"); return -1; }

    if (pid == 0) {
        /* Redirect stdin and stderr for child nodes */
        freopen("/dev/null", "r", stdin);
        freopen("/dev/null", "w", stderr);
        execl(g_ironstack_path, "ironstack", node->conf_path, NULL);
        perror("execl");
        _exit(1);
    }

    node->pid = pid;
    printf("  [ironsim] Node %s started (pid=%d)\n", node->name, pid);
    return pid;
}

static void stop_node(sim_node_t *node) {
    if (node->pid > 0) {
        kill(node->pid, SIGTERM);
        waitpid(node->pid, NULL, 0);
        printf("  [ironsim] Node %s stopped\n", node->name);
        node->pid = 0;
    }
    unlink(node->conf_path);
}

/* ---- Linux-side network wiring ---- */

static void wire_links(void) {
    sleep(2); /* Wait for TAPs to be created */

    /* Assign peer IPs on Linux side of each TAP */
    for (int i = 0; i < g_node_count; i++) {
        sim_node_t *n = &g_nodes[i];
        for (int j = 0; j < n->iface_count; j++) {
            node_iface_t *ifc = &n->ifaces[j];
            int a, b, c, d;
            sscanf(ifc->ip, "%d.%d.%d.%d", &a, &b, &c, &d);
            char peer_ip[32];
            snprintf(peer_ip, sizeof(peer_ip), "%d.%d.%d.2/%d", a, b, c, ifc->prefix_len);

            run_cmd("ip addr add %s dev %s 2>/dev/null", peer_ip, ifc->tap_name);
            run_cmd("ip link set %s up 2>/dev/null", ifc->tap_name);
        }
    }

    /* Add host routes for each node IP pointing to the correct TAP */
    for (int i = 0; i < g_node_count; i++) {
        sim_node_t *n = &g_nodes[i];
        for (int j = 0; j < n->iface_count; j++) {
            run_cmd("ip route add %s/32 dev %s 2>/dev/null",
                    n->ifaces[j].ip, n->ifaces[j].tap_name);
        }
    }

    /* Enable IP forwarding */
    run_cmd("echo 1 > /proc/sys/net/ipv4/ip_forward 2>/dev/null");

    /* Apply link impairments via tc netem */
    for (int i = 0; i < g_link_count; i++) {
        sim_link_t *l = &g_links[i];
        if (l->delay_ms == 0 && l->loss_pct == 0 && !l->reorder) continue;

        sim_node_t *na = &g_nodes[l->node_a];
        sim_node_t *nb = &g_nodes[l->node_b];
        const char *tap_a = na->ifaces[l->iface_a].tap_name;
        const char *tap_b = nb->ifaces[l->iface_b].tap_name;

        /* Apply netem on both TAP interfaces (bidirectional) */
        char netem[128] = "";
        if (l->delay_ms > 0)
            snprintf(netem + strlen(netem), sizeof(netem) - strlen(netem), " delay %dms", l->delay_ms);
        if (l->loss_pct > 0)
            snprintf(netem + strlen(netem), sizeof(netem) - strlen(netem), " loss %d%%", l->loss_pct);
        if (l->reorder)
            snprintf(netem + strlen(netem), sizeof(netem) - strlen(netem), " reorder 25%%");

        if (netem[0]) {
            run_cmd("tc qdisc add dev %s root netem%s 2>/dev/null", tap_a, netem);
            run_cmd("tc qdisc add dev %s root netem%s 2>/dev/null", tap_b, netem);
            printf("  [ironsim] Link %s-%s: netem%s\n", na->name, nb->name, netem);
        }
    }

    /* Print topology summary */
    printf("\n  [ironsim] Network wiring complete:\n");
    for (int i = 0; i < g_node_count; i++) {
        sim_node_t *n = &g_nodes[i];
        for (int j = 0; j < n->iface_count; j++) {
            printf("    %s: %s (%s/%d)\n", n->name, n->ifaces[j].tap_name,
                   n->ifaces[j].ip, n->ifaces[j].prefix_len);
        }
    }
}

/* ---- Cleanup ---- */

static void cleanup_netem(void) {
    for (int i = 0; i < g_node_count; i++) {
        for (int j = 0; j < g_nodes[i].iface_count; j++) {
            run_cmd("tc qdisc del dev %s root 2>/dev/null", g_nodes[i].ifaces[j].tap_name);
        }
    }
}

/* ---- Default 2-node topology ---- */

static void setup_default_topology(void) {
    strcpy(g_nodes[0].name, "a");
    strcpy(g_nodes[0].ifaces[0].ip, "10.0.1.1");
    g_nodes[0].ifaces[0].prefix_len = 24;
    g_nodes[0].iface_count = 1;

    strcpy(g_nodes[1].name, "b");
    strcpy(g_nodes[1].ifaces[0].ip, "10.0.2.1");
    g_nodes[1].ifaces[0].prefix_len = 24;
    g_nodes[1].iface_count = 1;

    g_node_count = 2;

    g_links[0].node_a = 0; g_links[0].iface_a = 0;
    g_links[0].node_b = 1; g_links[0].iface_b = 0;
    g_link_count = 1;
}

/* ---- Parse topology config ---- */

static int parse_topology(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) return -1;

    char line[256];
    while (fgets(line, sizeof(line), f)) {
        line[strcspn(line, "\r\n")] = 0;
        if (line[0] == '#' || line[0] == 0) continue;

        char tokens[8][64];
        int ntok = sscanf(line, "%63s %63s %63s %63s %63s %63s %63s %63s",
                          tokens[0], tokens[1], tokens[2], tokens[3],
                          tokens[4], tokens[5], tokens[6], tokens[7]);
        if (ntok < 2) continue;

        if (strcmp(tokens[0], "node") == 0) {
            /* node <name> ip <ip/prefix> [ip <ip/prefix>] */
            sim_node_t *node = &g_nodes[g_node_count];
            strncpy(node->name, tokens[1], MAX_NAME - 1);
            node->iface_count = 0;

            for (int t = 2; t < ntok - 1; t++) {
                if (strcmp(tokens[t], "ip") == 0 && t + 1 < ntok) {
                    char *slash = strchr(tokens[t + 1], '/');
                    if (slash) {
                        *slash = 0;
                        node_iface_t *ifc = &node->ifaces[node->iface_count];
                        strcpy(ifc->ip, tokens[t + 1]);
                        ifc->prefix_len = atoi(slash + 1);
                        node->iface_count++;
                    }
                    t++;
                }
            }
            g_node_count++;

        } else if (strcmp(tokens[0], "link") == 0 && ntok >= 3) {
            /* link <nodeA> <nodeB> [delay <N>ms] [loss <N>%] [reorder] */
            int a = -1, b = -1;
            for (int i = 0; i < g_node_count; i++) {
                if (strcmp(g_nodes[i].name, tokens[1]) == 0) a = i;
                if (strcmp(g_nodes[i].name, tokens[2]) == 0) b = i;
            }
            if (a < 0 || b < 0) continue;

            sim_link_t *l = &g_links[g_link_count];
            l->node_a = a; l->node_b = b;
            l->delay_ms = 0; l->loss_pct = 0; l->reorder = 0;

            /* Determine which interface on each node connects to the other */
            /* Use the first interface that shares a subnet, or default to 0 */
            l->iface_a = 0; l->iface_b = 0;
            for (int ia = 0; ia < g_nodes[a].iface_count; ia++) {
                for (int ib = 0; ib < g_nodes[b].iface_count; ib++) {
                    int aa, ab, ac, ba, bb, bc;
                    sscanf(g_nodes[a].ifaces[ia].ip, "%d.%d.%d.%*d", &aa, &ab, &ac);
                    sscanf(g_nodes[b].ifaces[ib].ip, "%d.%d.%d.%*d", &ba, &bb, &bc);
                    if (aa == ba && ab == bb && ac == bc) {
                        l->iface_a = ia; l->iface_b = ib;
                    }
                }
            }

            /* Parse optional impairments */
            for (int t = 3; t < ntok; t++) {
                if (strcmp(tokens[t], "delay") == 0 && t + 1 < ntok)
                    l->delay_ms = atoi(tokens[++t]);
                else if (strcmp(tokens[t], "loss") == 0 && t + 1 < ntok)
                    l->loss_pct = atoi(tokens[++t]);
                else if (strcmp(tokens[t], "reorder") == 0)
                    l->reorder = 1;
            }

            g_link_count++;
        }
    }
    fclose(f);
    return 0;
}

/* ---- Main ---- */

int main(int argc, char **argv) {
    signal(SIGINT, signal_handler);
    signal(SIGTERM, signal_handler);

    printf("╔══════════════════════════════════════════╗\n");
    printf("║       ironsim — Network Emulator         ║\n");
    printf("╚══════════════════════════════════════════╝\n\n");

    /* Find ironstack binary */
    if (access("../ironstack/ironstack", X_OK) == 0)
        strcpy(g_ironstack_path, "../ironstack/ironstack");
    else if (access("./ironstack/ironstack", X_OK) == 0)
        strcpy(g_ironstack_path, "./ironstack/ironstack");
    else {
        fprintf(stderr, "Error: cannot find ironstack binary\n");
        return 1;
    }

    /* Parse topology or use default */
    if (argc >= 2) {
        if (parse_topology(argv[1]) != 0) {
            fprintf(stderr, "Error: cannot parse topology file: %s\n", argv[1]);
            return 1;
        }
        printf("  [ironsim] Loaded topology: %s\n", argv[1]);
    } else {
        setup_default_topology();
        printf("  [ironsim] Using default 2-node topology\n");
    }

    printf("  [ironsim] Nodes: %d, Links: %d\n\n", g_node_count, g_link_count);

    /* Generate configs and spawn nodes */
    for (int i = 0; i < g_node_count; i++)
        generate_node_conf(&g_nodes[i]);

    for (int i = 0; i < g_node_count; i++)
        spawn_node(&g_nodes[i]);

    /* Wire up Linux-side networking */
    wire_links();

    printf("\n  [ironsim] Topology is UP. Press Ctrl+C to stop.\n\n");

    /* Wait until interrupted */
    while (g_running)
        sleep(1);

    /* Shutdown */
    printf("\n  [ironsim] Shutting down...\n");
    cleanup_netem();
    for (int i = 0; i < g_node_count; i++)
        stop_node(&g_nodes[i]);

    printf("  [ironsim] Done.\n");
    return 0;
}
