/*
 * ironsim — Network Emulator
 * Spawns multiple ironstack instances connected by virtual links.
 *
 * Usage: sudo ./ironsim [topology.conf]
 * Default: 2-node linear topology
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <unistd.h>
#include <signal.h>
#include <sys/wait.h>
#include <sys/types.h>

#define MAX_NODES    8
#define MAX_LINKS    8
#define MAX_NAME     32
#define MAX_PATH     256

typedef struct {
    char name[MAX_NAME];
    char ip[32];
    int  prefix_len;
    char tap_name[MAX_NAME];   /* TAP interface for this node */
    pid_t pid;
    char conf_path[MAX_PATH];  /* Generated config file */
} sim_node_t;

typedef struct {
    int node_a;
    int node_b;
    char veth_a[MAX_NAME];  /* veth end on node A side */
    char veth_b[MAX_NAME];  /* veth end on node B side */
} sim_link_t;

static sim_node_t g_nodes[MAX_NODES];
static int g_node_count = 0;
static sim_link_t g_links[MAX_LINKS];
static int g_link_count = 0;
static volatile int g_running = 1;
static char g_ironstack_path[MAX_PATH] = "./ironstack/ironstack";

static void signal_handler(int sig) {
    (void)sig;
    g_running = 0;
}

/* ---- System commands ---- */

static int run_cmd(const char *fmt, ...) {
    char cmd[512];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(cmd, sizeof(cmd), fmt, ap);
    va_end(ap);
    return system(cmd);
}

/* ---- Network setup ---- */

static int create_veth_pair(const char *name_a, const char *name_b) {
    run_cmd("ip link add %s type veth peer name %s 2>/dev/null", name_a, name_b);
    run_cmd("ip link set %s up", name_a);
    run_cmd("ip link set %s up", name_b);
    return 0;
}

static void destroy_veth_pair(const char *name_a) {
    run_cmd("ip link delete %s 2>/dev/null", name_a);
}

static int create_bridge_for_link(sim_link_t *link, sim_node_t *a, sim_node_t *b) {
    /* Create veth pair */
    snprintf(link->veth_a, MAX_NAME, "sim-%s", a->name);
    snprintf(link->veth_b, MAX_NAME, "sim-%s", b->name);
    create_veth_pair(link->veth_a, link->veth_b);

    /* Assign peer IPs so traffic can flow between nodes' TAPs */
    /* Node A's TAP will be bridged with veth_a */
    /* Node B's TAP will be bridged with veth_b */
    /* Actually: each node's ironstack reads from its own TAP.
       We need Linux to route between the TAPs.
       Simplest: assign IPs on the veth ends and enable forwarding. */

    /* Assign IP on veth_a (node A's subnet, peer address) */
    char ip_a[32], ip_b[32];
    snprintf(ip_a, sizeof(ip_a), "%s/%d", a->ip, a->prefix_len);
    snprintf(ip_b, sizeof(ip_b), "%s/%d", b->ip, b->prefix_len);

    /* The veth pair connects the two nodes' subnets.
       Each ironstack creates its own TAP. Linux needs to forward between them.
       Strategy: put each veth end in a bridge with the corresponding TAP. */

    /* Create bridges */
    char br_a[MAX_NAME], br_b[MAX_NAME];
    snprintf(br_a, MAX_NAME, "br-%s", a->name);
    snprintf(br_b, MAX_NAME, "br-%s", b->name);

    run_cmd("ip link add %s type bridge 2>/dev/null", br_a);
    run_cmd("ip link add %s type bridge 2>/dev/null", br_b);
    run_cmd("ip link set %s up", br_a);
    run_cmd("ip link set %s up", br_b);

    /* Add TAP and veth to bridges (TAP will be created by ironstack later) */
    /* We'll add them after ironstack starts */

    return 0;
}

/* ---- Config generation ---- */

static void generate_node_conf(sim_node_t *node) {
    snprintf(node->conf_path, MAX_PATH, "/tmp/ironsim_%s.conf", node->name);
    FILE *f = fopen(node->conf_path, "w");
    if (!f) { perror("fopen"); return; }

    /* Use node-specific TAP name */
    snprintf(node->tap_name, MAX_NAME, "iron-%s", node->name);

    fprintf(f, "# Auto-generated by ironsim for node %s\n", node->name);
    fprintf(f, "interface %s mac 02:00:00:00:00:%02x ip %s/%d\n",
            node->tap_name, (unsigned)(node->name[0]),
            node->ip, node->prefix_len);

    /* Connected route for own subnet */
    int a, b, c, d;
    sscanf(node->ip, "%d.%d.%d.%d", &a, &b, &c, &d);
    fprintf(f, "route %d.%d.%d.0/%d dev %s\n", a, b, c, node->prefix_len, node->tap_name);

    /* Permit all traffic */
    fprintf(f, "acl permit icmp any any port 0\n");
    fprintf(f, "acl permit tcp any any port 7\n");

    fclose(f);
    printf("  [ironsim] Generated config: %s\n", node->conf_path);
}

/* ---- Node management ---- */

static pid_t spawn_node(sim_node_t *node) {
    pid_t pid = fork();
    if (pid < 0) { perror("fork"); return -1; }

    if (pid == 0) {
        /* Child: exec ironstack with the generated config */
        execl(g_ironstack_path, "ironstack", node->conf_path, NULL);
        perror("execl");
        _exit(1);
    }

    node->pid = pid;
    printf("  [ironsim] Node %s started (pid=%d, tap=%s, ip=%s/%d)\n",
           node->name, pid, node->tap_name, node->ip, node->prefix_len);
    return pid;
}

static void stop_node(sim_node_t *node) {
    if (node->pid > 0) {
        kill(node->pid, SIGTERM);
        waitpid(node->pid, NULL, 0);
        printf("  [ironsim] Node %s stopped (pid=%d)\n", node->name, node->pid);
        node->pid = 0;
    }
    /* Cleanup temp config */
    unlink(node->conf_path);
}

/* ---- Linux-side network wiring ---- */

static void wire_links(void) {
    /* Wait for ironstack to create TAP interfaces */
    sleep(2);

    for (int i = 0; i < g_node_count; i++) {
        sim_node_t *n = &g_nodes[i];
        /* Assign a peer IP on the Linux side of each TAP.
           Node has x.x.x.1, Linux gets x.x.x.2 */
        int a, b, c, d;
        sscanf(n->ip, "%d.%d.%d.%d", &a, &b, &c, &d);
        char peer_ip[32];
        snprintf(peer_ip, sizeof(peer_ip), "%d.%d.%d.2/%d", a, b, c, n->prefix_len);

        run_cmd("ip addr add %s dev %s 2>/dev/null", peer_ip, n->tap_name);
        run_cmd("ip link set %s up 2>/dev/null", n->tap_name);
        printf("  [ironsim] Linux: %s on %s\n", peer_ip, n->tap_name);
    }

    /* Enable IP forwarding so Linux routes between subnets */
    run_cmd("echo 1 > /proc/sys/net/ipv4/ip_forward 2>/dev/null");
}

/* ---- Default 2-node topology ---- */

static void setup_default_topology(void) {
    /* Node A */
    strcpy(g_nodes[0].name, "a");
    strcpy(g_nodes[0].ip, "10.0.1.1");
    g_nodes[0].prefix_len = 24;

    /* Node B */
    strcpy(g_nodes[1].name, "b");
    strcpy(g_nodes[1].ip, "10.0.2.1");
    g_nodes[1].prefix_len = 24;

    g_node_count = 2;

    /* Link A-B */
    g_links[0].node_a = 0;
    g_links[0].node_b = 1;
    g_link_count = 1;
}

/* ---- Parse topology config ---- */

static int parse_topology(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) return -1;

    char line[256];
    while (fgets(line, sizeof(line), f)) {
        line[strcspn(line, "\r\n")] = 0;
        if (line[0] == '#' || line[0] == 0) continue;

        char cmd[32], arg1[64], arg2[64], arg3[64];
        int n = sscanf(line, "%31s %63s %63s %63s", cmd, arg1, arg2, arg3);
        if (n < 2) continue;

        if (strcmp(cmd, "node") == 0 && n >= 3) {
            /* node <name> ip <ip>/<prefix> */
            sim_node_t *node = &g_nodes[g_node_count];
            strncpy(node->name, arg1, MAX_NAME - 1);
            /* Parse ip from arg2 (format: "ip") and arg3 (format: "10.0.1.1/24") */
            if (strcmp(arg2, "ip") == 0 && n >= 4) {
                char *slash = strchr(arg3, '/');
                if (slash) {
                    *slash = 0;
                    strcpy(node->ip, arg3);
                    node->prefix_len = atoi(slash + 1);
                }
            }
            g_node_count++;
        } else if (strcmp(cmd, "link") == 0 && n >= 3) {
            /* link <nodeA> <nodeB> */
            int a = -1, b = -1;
            for (int i = 0; i < g_node_count; i++) {
                if (strcmp(g_nodes[i].name, arg1) == 0) a = i;
                if (strcmp(g_nodes[i].name, arg2) == 0) b = i;
            }
            if (a >= 0 && b >= 0) {
                g_links[g_link_count].node_a = a;
                g_links[g_link_count].node_b = b;
                g_link_count++;
            }
        }
    }
    fclose(f);
    return 0;
}

/* ---- Main ---- */

int main(int argc, char **argv) {
    signal(SIGINT, signal_handler);
    signal(SIGTERM, signal_handler);

    printf("╔══════════════════════════════════════════╗\n");
    printf("║       ironsim — Network Emulator         ║\n");
    printf("╚══════════════════════════════════════════╝\n\n");

    /* Find ironstack binary path (relative to ironsim) */
    /* Assume ironsim is in build/ironsim/ and ironstack is in build/ironstack/ */
    snprintf(g_ironstack_path, MAX_PATH, "%s/../ironstack/ironstack",
             argc > 0 ? "." : ".");

    /* Check if ironstack exists */
    if (access("../ironstack/ironstack", X_OK) == 0)
        strcpy(g_ironstack_path, "../ironstack/ironstack");
    else if (access("./ironstack/ironstack", X_OK) == 0)
        strcpy(g_ironstack_path, "./ironstack/ironstack");
    else {
        fprintf(stderr, "Error: cannot find ironstack binary\n");
        return 1;
    }

    /* Parse topology or use default */
    if (argc >= 2) {
        if (parse_topology(argv[1]) != 0) {
            fprintf(stderr, "Error: cannot parse topology file: %s\n", argv[1]);
            return 1;
        }
        printf("  [ironsim] Loaded topology: %s\n", argv[1]);
    } else {
        setup_default_topology();
        printf("  [ironsim] Using default 2-node topology\n");
    }

    printf("  [ironsim] Nodes: %d, Links: %d\n\n", g_node_count, g_link_count);

    /* Generate configs and spawn nodes */
    for (int i = 0; i < g_node_count; i++) {
        generate_node_conf(&g_nodes[i]);
    }

    for (int i = 0; i < g_node_count; i++) {
        spawn_node(&g_nodes[i]);
    }

    /* Wire up Linux-side networking */
    wire_links();

    printf("\n  [ironsim] Topology is UP. Press Ctrl+C to stop.\n");
    printf("  [ironsim] Test with: ping 10.0.1.1 or ping 10.0.2.1\n\n");

    /* Wait until interrupted */
    while (g_running) {
        sleep(1);
    }

    /* Shutdown */
    printf("\n  [ironsim] Shutting down...\n");
    for (int i = 0; i < g_node_count; i++) {
        stop_node(&g_nodes[i]);
    }

    /* Cleanup veth pairs */
    for (int i = 0; i < g_link_count; i++) {
        if (g_links[i].veth_a[0])
            destroy_veth_pair(g_links[i].veth_a);
    }

    printf("  [ironsim] Done.\n");
    return 0;
}
