# IronNet Virtual Router Configuration
# Usage: sudo ./ironstack/ironstack router.conf

interface iron0 mac 02:00:00:00:00:01 ip 10.0.1.1/24
interface iron1 mac 02:00:00:00:00:02 ip 10.0.2.1/24

route 10.0.1.0/24 dev iron0
route 10.0.2.0/24 dev iron1
route 0.0.0.0/0 via 10.0.1.254 dev iron0

acl permit tcp any any port 80
acl permit icmp any any port 0
acl deny tcp any any port 22
acl permit tcp any any port 9999
