# ironsim topology: 3-node linear with impairments
#
#   Node A (10.0.1.1) <--5ms--> Node B (10.0.1.254, 10.0.2.254) <--10ms/1% loss--> Node C (10.0.2.1)
#
# Node B is a router between subnet 10.0.1.0/24 and 10.0.2.0/24

node a ip 10.0.1.1/24
node b ip 10.0.1.254/24 ip 10.0.2.254/24
node c ip 10.0.2.1/24

link a b delay 5ms
link b c delay 10ms loss 1%
